### ISSUE TITLE
Error when run the sample project

### ISSUE THREAD

**Issue by AmnaButt** [gerardo-lijs/CrystalReportsRunner#31]
### Discussed in https://github.com/gerardo-lijs/CrystalReportsRunner/discussions/30

<div type='discussions-op-text'>

<sup>Originally posted by **AmnaButt** July 23, 2024</sup>
I have been getting following error when I run the sample project here, no changes has been done

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'CrystalDecisions.ReportAppServer.CommLayer, Version=13.0.4000.0, Culture=neutral, PublicKeyToken=692fbea5521e1304' or one of its dependencies. The system cannot find the file specified.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Send(SendOrPostCallback d, Object state)
   at LijsDev.CrystalReportsRunner.Shell.WinFormsReportRunner.ShowReport(Report report, ReportViewerSettings viewerSettings, WindowHandle owner) in C:\Users\AmnaButt\Downloads\CrystalReportsRunner-main\CrystalReportsRunner-main\src\LijsDev.CrystalReportsRunner.Shell\WinFormsReportRunner.cs:line 71
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PipeMethodCalls.RequestHandler`1.<GetTypedResponseForRequest>d__7.MoveNext()</div>

**Comment by gerardo-lijs** [comment]
Hi, sorry for the delay, I was on holidays and catching up with stuff.

This kind of errors, usually occure when the runtime you are using does not match the Crystal Reports Runtime installed in your system. It has to match the version and the architecture (32 or 64bits). Please check which runtime you have installed in your system and use the matching Runner.

In the future, I can improve this error messages, so that I tells you what runtime you are targeting and also what runtimes are installed in your system, instead of the generic Could not load dll
