### ISSUE TITLE
Subreports do not see parameters

### ISSUE THREAD

**Issue by jaceks2106** [gerardo-lijs/CrystalReportsRunner#9]
Hi,

I have a problem with linked subreports and passed parameters. The exception from SAP is thrown that some parameter values are missing. Parameters are named exactly the same in the main report and subreport.

```
CrystalDecisions.CrystalReports.Engine.ParameterFieldCurrentValueException: Missing parameter values. ---> System.Runtime.InteropServices.COMException: Missing parameter values.
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
   --- End of inner exception stack trace ---
   at CrystalDecisions.ReportAppServer.ConvertDotNetToErom.ThrowDotNetException(Exception e)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.ExportToStream(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.Export(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.ReportDocument.ExportToDisk(ExportFormatType formatType, String fileName)
   at LijsDev.CrystalReportsRunner.Shell.WinFormsReportRunner.Export(Report report, ReportExportFormats exportFormat, String destinationFilename, Boolean overwrite) in D:\work\Projects\CrystalReportsRunner-main\src\LijsDev.CrystalReportsRunner.Shell\WinFormsReportRunner.cs:line 38
```

**Comment by gerardo-lijs** [comment]
Hi, we are using it with reports and subreports that use parameters and it's been working fine for us. The code that configures the parameters is here -> https://github.com/gerardo-lijs/CrystalReportsRunner/blob/37bb86657871eaa5bf2d3f8cf68b609dd88e4678/src/LijsDev.CrystalReportsRunner/shared/ReportUtils.cs#L102

You might be able to compare against how you are currently configuring your reports in Crystal Reports and might find something different. If you can create a small repo with your subreport so that we can run it and try to find the issue we are also willing to help.

This repro repo should be a simple .NET 48 or 45 project in Winforms or WPF that just loads and shows your report with subreports. We can then compare this code against how the current runner is configuring Crystal Reports and look for the difference/issue.

Please let me know the results, and we can follow up on this, but unfortunately with the current details you provided I'm unable to test/repro the issue in order to help.

**Comment by jaceks2106** [comment]
Thanks for the quick response. It's kind of problematic to give you the file, as it's really sensitive from the business perspective.

I have another question, that you probably can answer. The problem occurs on report, which has 2 subreports, but the one parameter used in both subreports is not linked to the root report. Once I create such parameter in root and link it, then it's ok.

**Comment by gerardo-lijs** [comment]
Maybe it was possible to build a fake report with subreport that fails for the repro in order not to put any sensitive data. Anyways, if it's working for some reports and not for this one in particular, it might be the way parameters are set for the whole document and not for each individual subreport. The link I sent before, shows that in line 102 of ReportUtils.cs. So, it could be possible to change this code, so that it also loops in subreports parameters. This is something that we don't use and we will need to test it with a fake/sample report. We can create a branch and try it out together and pretty sure it will end up working. Do you have the code you used to set report and subreports parameters with Crystal Reports to use as starting point?

**Comment by jaceks2106** [comment]
```
        using var engine = ConfigureEngine();

        var con = ConfigureConnection();
        var report = new LijsDev.CrystalReportsRunner.Core.Report(reportPath, "GeneratedReport")
        {
          Connection = con,
        };

        foreach (var rparam in reportParameters)
        {
          if (rparam.Values.Count < 2)
          {
            report.Parameters.Add(rparam.ParameterName, rparam.Values.First()); // rparam.Values is a List<string>
          }
          else
          {
            report.Parameters.Add(rparam.ParameterName, rparam.Values);
          }
        }

        var expectedParameters = await engine.GetReportParameters(report);
        engine.GetReportParameters(report).GetAwaiter().GetResult();
        expectedParametersList = string.Join(',', expectedParameters
          .Select(p => $"{p.ParameterName}({(ParameterValueKind)p.ParameterType})"));

        var expectedSystemParameter = expectedParameters.FirstOrDefault(p => p.ParameterName.Contains("systemid", StringComparison.OrdinalIgnoreCase));
        if (expectedSystemParameter is not null)
        {
          report.Parameters.Add(expectedSystemParameter.ParameterName, 1);
        }
        var reportFormat = GetCrystalFormat(format);
        
        await engine.Export(report, reportFormat, resultPdf);
```

This is the main code for passing params and exporting report. The private methods are just helpers/mappers, not so crucial.

**Comment by gerardo-lijs** [comment]
Hi, I will try to create a branch to test subreports parameters today after work. The code I was asking was actually not how to pass parameter to this library, but for Crystal Reports itself. But don't worry, will try to create a simple sample so you can see what I mean.

Not related, but you should probably get rid of the duplicated line of code engine.GetReportParameters(report).GetAwaiter().GetResult();  since you are using it correctly with await in the previous line.

**Comment by jaceks2106** [comment]
> Not related, but you should probably get rid of the duplicated line of code engine.GetReportParameters(report).GetAwaiter().GetResult(); since you are using it correctly with await in the previous line.

Of course, it was a mistake during copy. We use unfortunately GetAwaiter().GetResult() instead of await, but it's too painful for me, so I wanted to paste the code the way how it should look like :D.

**Comment by gerardo-lijs** [comment]
Hi, I created a test branch in CrystalReportsRunner.Samples repository. I created a report with subreports and I added a parameter to the subreport that does not exists in the main report. See https://github.com/gerardo-lijs/CrystalReportsRunner.Samples/tree/issue-9/subreport-params

Everything is working fine for me and I did not get any exception. Parameters were sent correctly to the subreport. Please review the branch/code and let me know if I can help you with your specific problem.

You can create a fork of the sample repo and try with your own report and changes and if you share that with me later we can see what kind of issue you are experiencing. As far as I was able to test, everything is working fine.

See below how the report parameters are defined

![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/62c04add-199e-49ad-bbba-7b2f9a5342b8)
![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/91eb5dd4-6eea-4a91-bef8-ac020c61a7f4)

And in the source code

![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/83f4c999-5dc1-419c-8dd0-c5150594d74e)

And sample working fine

![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/809f02a5-6081-473e-b39e-b346ee6ee03b)

**Comment by jaceks2106** [comment]
Thanks, will check that!

**Comment by jaceks2106** [comment]
Your samples helped me a lot in finding the problem. Thanks a lot.

But look at the case. I have a little bit wrongly prepared report (let's assume that we cannot change it for now), which has two subreports. Both accept parameter with same name "SystemID". When I add this parameter to dictionary and click Show Report, then the prompt asks me to fill the value of the "SystemID" but just for one subreport. It looks like, the parameter is taken by one subreport and the second is left with nothing. When I properly prepare report with linking subreports' parameters to the root one, everything is ok.
